commerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from .views import index, productDetailsView,shop_cart,remove_from_cart,shopView,orders,add_to_cart,signuppage,loginpage,logoutUser,crotchetsView,remove_single_item_from_cart,checkoutview,PaymentView,stringArtsView,yarnAccessoriesView,adminDash,admin_allproductsView,admin_crotchetbagsView,admin_crotchetproductsView,admin_stringsView,admin_yarnView,delete_product,AddProductView,crotchetBagsView,crotchetProductsView,CallBackURLDetailsAPI,search_product
app_name = 'commerce'
urlpatterns = [ 
    
    path("",index,name="index"),
    path("shop",shopView.as_view(),name="shop"),
    path("shop-cart",shop_cart.as_view(),name="shop-cart"),
    path("product-details/<slug>/",productDetailsView.as_view(),name="product-details"),
    path("add-to-cart/<slug>/",add_to_cart,name="add-to-cart"),
    path("remove-from-cart/<slug>/",remove_from_cart,name="remove-from-cart"),
    path("remove_single_item_from_cart/<slug>/",remove_single_item_from_cart,name="remove_single_item_from_cart"),
    path("string-arts",stringArtsView.as_view(),name="string-arts"),
    path("crotchets",crotchetsView.as_view(),name="crotchets"),
    path("crotchetBags",crotchetBagsView.as_view(),name="crotchetbags"),
    path("crotchetProducts",crotchetProductsView.as_view(),name="crotchetproducts"),
    path("yarnaccessories",yarnAccessoriesView.as_view(),name="yarnaccessories"),
    path("checkout",checkoutview.as_view(),name="checkout"),
    path("orders",orders,name="orders"),
    path("signuppage",signuppage,name="signuppage"),
    path("loginpage",loginpage,name="loginpage"),
    path('logout/', logoutUser, name='logout'),
    # path('daraja/stk-push', stk_push_callback, name='mpesa_stk_push_callback'),
    # path('mpesa/', mpesaPayment, name='mpesa'),
    path('payment/<payment_option>/',PaymentView.as_view(),name="payment"),
    path('adminDash/',adminDash,name="admin-dashboard"),
    path('adminproducts/',admin_allproductsView.as_view(),name="admin_allproducts"),
    path('admincrotchetbags/',admin_crotchetbagsView.as_view(),name="admin_crotchetbags"),
    path('admincrotchetproducts/',admin_crotchetproductsView.as_view(),name="admin_crotchetproducts"),
    path('adminstringarts/',admin_stringsView.as_view(),name="admin_stringarts"),
    path('adminyarn/',admin_yarnView.as_view(),name="admin_yarn"),
    path("delete_product/<slug>/",delete_product,name="delete_product"),
    path("addProduct/",AddProductView.as_view(),name="add_product"),
    path("search_product/",search_product,name="search_product"),


    #APIs
    path("callbacks/",CallBackURLDetailsAPI,name="callback"),


] 

if settings.DEBUG: 
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("",include("commerce.urls",namespace="commerce")),
    path("deliveries",include("delivery.urls",namespace="delivery"))

]

commerce/views.py
from ast import Pass
from cProfile import label
from email import message
from multiprocessing import context
from turtle import title
from unicodedata import category
from django.shortcuts import render,redirect, get_object_or_404
from django.views import View
import phonenumbers
from pytz import timezone
from requests import Response, request
from .models import Item,Order,OrderItem,ShippingAddress,CallBackURL
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm,CheckoutForm,AddProductForm,PaymentForm
from django.views.generic import ListView,DetailView
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import requests
# from django_daraja.mpesa.core import MpesaClient
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .serializers import MpesaCheckoutSerializer,CallBackSerializer
from bootstrap_modal_forms.generic import BSModalCreateView
from .mpesa import lipa_na_mpesa
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import base64
from datetime import datetime
import requests
from requests.auth import HTTPBasicAuth
import json
import pdb

# from .util import MpesaGateWay



# Create your views here.

#homepage
def index(request):
    items = Item.objects.all(),
    
    new_crotchets = Item.objects.filter(category='Crotchet Products').first() 
    new_bag = Item.objects.filter(category='Crotchet Bag').order_by('-id').first()
    new_art = Item.objects.filter(category='String Art').order_by('-id').first()
    new_acc = Item.objects.filter(category='Yarn & Accessories').order_by('-id').first()
    print(new_bag)
    context = {
        "items":items,
        "new_crotchets": new_crotchets,
        "new_art":new_art,
        "new_acc":new_acc,
        "new_bag":new_bag,

    }
    return render(request,'index.html',context)
 

#includes all products
class shopView(ListView):
    paginate_by=10
    model = Item
    queryset=Item.objects.all().order_by('-id')
   
    template_name = "shop.html"

#individual products details
class productDetailsView(DetailView):
    model= Item
    template_name = "product-details.html"
    # images = Item.objects.get()



class shop_cart(View):
    model=Order
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user=self.request.user,ordered=False)
            context={
                "order":order
            }
            return render(self.request,"shop-cart.html",context)
        except ObjectDoesNotExist:
            messages.error(self.request,"You do not have an active order")
            return redirect("commerce:index")


class checkoutview(LoginRequiredMixin,View):
    model=Order
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user=self.request.user,ordered=False)
            form = CheckoutForm()
            context = {
            "form": form,
            "order":order
            }
            return render(self.request, "checkout.html",context)
        except ObjectDoesNotExist:
            messages.error(self.request,"You do not have an active order")
            return redirect("commerce:index")
            

    def post(self,*args,**kwargs):
        form = CheckoutForm(self.request.POST or None)
        paymentForm =  PaymentForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user,ordered=False)
            context = {

            "paymentForm": paymentForm,
            "order":order
            }
            if form.is_valid():
                
                firstname = form.cleaned_data.get("firstname")
                lastname = form.cleaned_data.get("lastname")
                county = form.cleaned_data.get("county")
                town = form.cleaned_data.get("town")
                street_address = form.cleaned_data.get("street_address")
                apartment_address = form.cleaned_data.get("apartment_address")
                zip = form.cleaned_data.get("zip")
                phone = form.cleaned_data.get("phone")
                email = form.cleaned_data.get("email")
                # save_info = form.cleaned_data.get("save_info")
                payment_option = form.cleaned_data.get("payment_option")
                order_notes = form.cleaned_data.get("order_notes")
                
                shippingaddress = ShippingAddress(
                    user = self.request.user,
                    firstname=firstname,
                    lastname= lastname,
                    county=county,
                    town=town,
                    street_address= street_address,
                    apartment_address=apartment_address,
                    zip=zip,
                    phone=phone,
                    email=email,
                    order_notes= order_notes,
                    payment_option=payment_option,
                )
                shippingaddress.save()
                order.shipping_address = shippingaddress
                order.save()
                context = {
                "paymentForm": paymentForm,
                "order":order
                    }
                if shippingaddress.payment_option == "M":
                    print(shippingaddress.payment_option)
                    return redirect("commerce:payment",str(shippingaddress.payment_option))

                elif shippingaddress.payment_option == "P":
                    pass

                elif shippingaddress.payment_option == "S":
                    pass

                

            messages.warning(self.request,"Failed Checkout")
            return redirect("commerce:checkout")

        except ObjectDoesNotExist:
            messages.error(self.request,"You do not have an active order")
            return redirect("commerce:checkout")

class PaymentView(View):
    model=Order
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user=self.request.user,ordered=False)
            paymentForm = PaymentForm()
            context = {
            "paymentForm": paymentForm,
            "order":order
            }
          
            return render(self.request, "payment.html",context)
        except ObjectDoesNotExist:
            messages.error(self.request,"You do not have an active order")
            return redirect("commerce:index")
    def post(self,*args,**kwargs):
        paymentForm =  PaymentForm(self.request.POST or None, self.request.FILES)
        try:
            order = Order.objects.get(user=self.request.user,ordered=False)
            
            context = {
            "paymentForm": paymentForm,
            "order":order
            }
            phonenumber = self.request.POST.get("phonenumber")
            amount = order.get_order_total()
           
            # lipa_na_mpesa(amount,phonenumber)
            
           
                
                

            return render(self.request,"payment.html",context)
            print("NOT VALID")
            return redirect("commerce:checkout")
        

        except ObjectDoesNotExist:
            messages.error(self.request,"You do not have an active order")
            return redirect()
            

class stringArtsView(ListView):
    model=Item
    queryset  = Item.objects.filter(category='String Art').order_by('-id')
    context = {

    }
    template_name="string_arts.html"


class crotchetsView(ListView):
    model = Item
    queryset=Item.objects.filter(category='Crotchet Products') | Item.objects.filter(category='Crotchet Bag').order_by('-id')
    

    template_name ="crotchets.html"

class crotchetBagsView(ListView):
    model = Item
    queryset= Item.objects.filter(category='Crotchet Bag').order_by('-id')
    

    template_name ="crotchetsbags.html"

class crotchetProductsView(ListView):
    model = Item
    queryset= Item.objects.filter(category='Crotchet Products').order_by('-id')
    

    template_name ="crotchetsProducts.html"


class yarnAccessoriesView(ListView):
    model=Item
    queryset  = Item.objects.filter(category='Yarn & Accessories').order_by('-id')
    context = {

    }
    template_name="yarnaccessories.html"

@login_required
def orders(request):
    all_oders = Order.objects.filter(user=request.user).order_by('-ordered_date')
    print(all_oders)
    context = {
        "all_orders":all_oders
    }

    return render(request,"orders.html",context)


#userRegistration page
def signuppage(request):
    form = CreateUserForm()
 
    if request.method == "POST":
        form =CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Registered Successfully. Login to continue")
            return redirect("commerce:loginpage")

    context = {
        "form":form
    }
    return render(request,"auth/signup.html",context)

#userloginpage
def loginpage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username,
                            password=password)
        print(user)
        if user is not None:
            login(request, user)
            messages.success(request, 'Logged in as' + ' ' + username)
            return redirect("commerce:index")
            # if user.is_admin:
            #     return redirect('dashboard')
            # if user.is_customer:
            #     return redirect('home')
        else:
            messages.error(request, 'Invalid Username and/or Password')

    context = {}

commerce/templates/crotchetsProducts.html
{% extends 'base.html' %}
{% load static %}


{% block content%}

<body>
 <style>.grid-item {
    float: left;
  }
  
  .grid-item img {
    display: block;
    max-width: 100%;
  }</style>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    {% include "wrapper.html" %}
  
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->

    <!-- Header Section End -->

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="{% url 'commerce:index' %}"><i class="fa fa-home"></i> Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Shop Section Begin -->
   
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
                    <div class="shop__sidebar">
                         <div class="sidebar__filter">
                            <div class="section-title">
                                <h4>Shop by price</h4>
                            </div>
                            <!-- <div class="filter-range-wrap">
                                <div class="price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content"
                                data-min="0" data-max="3000"></div>
                                <div class="range-slider">
                                    <div class="price-input">
                                        <p>Price:</p>
                                        <input type="text" id="minamount">
                                        <input type="text" id="maxamount">
                                    </div>
                                </div>
                            </div>
                            <a href="#">Filter</a> -->
                        </div> 

                        <div class="sidebar__color">
                            <div class="section-title">
                                <h4>Shop by Color</h4>
                            </div>
                            <!-- <div class="size__list color__list">
                                <label for="black">
                                    Blacks
                                    <input type="checkbox" id="black">
                                    <span class="checkmark"></span>
                                </label>
                                <label for="whites">
                                    Whites
                                    <input type="checkbox" id="whites">
                                    <span class="checkmark"></span>
                                </label>
                                <label for="reds">
                                    Reds
                                    <input type="checkbox" id="reds">
                                    <span class="checkmark"></span>
                                </label>
                                <label for="greys">
                                    Greys
                                    <input type="checkbox" id="greys">
                                    <span class="checkmark"></span>
                                </label>
                                <label for="blues">
                                    Blues
                                    <input type="checkbox" id="blues">
                                    <span class="checkmark"></span>
                                </label>
                                <label for="beige">
                                    Beige Tones
                                    <input type="checkbox" id="beige">
                                    <span class="checkmark"></span>
                                </label>
                                <label for="greens">
                                    Greens
                                    <input type="checkbox" id="greens">
                                    <span class="checkmark"></span>
                                </label>
                                <label for="yellows">
                                    Yellows
                                    <input type="checkbox" id="yellows">
                                    <span class="checkmark"></span>
                                </label>
                            </div> -->
                        </div>
                    </div>
                </div>
                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 ">
                    <div class="row" data-masonry='{"percentPosition": true }'>
                      
                        {% for items in object_list %}
                        
                        <div class="col-xs-4 col-sm-3 col-md-3 col-lg-3 " >
                            <a href="{{ items.get_absolute_url }}">
                            <div class="product__item" >
                               
                                <div class="product__item__pic set-bg" data-setbg="{{items.image.url}}" style="border-radius: 20px; height: 280px; width: 180;">
                           
                                    <div class="label new">New</div>
                                    <ul class="product__hover">
                                        <li><a href="{% static 'img/shop/shop-1.jpg' %}" class="image-popup"><span class="arrow_expand"></span></a></li>
                                        <li><a href="#"><span class="icon_heart_alt"></span></a></li>
                                        <li><a href="#"><span class="icon_bag_alt"></span></a></li>
                                    </ul>
                                </div>
                           
                                <div class="product__item__text">
                                    <h6><b><a href="#">{{items.title}}</a></b></h6>
                                    <div class="product__price"> Ksh
                                        {%if items.discount_price %}
                                        {{items.discount_price}}
                                        {%else%}
                                        {{items.price}}
                                        {%endif%}
                                    </div>
                                    <div class="rating">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                               
                                </div>
                                </a>
                            </div>
                            
                        </div>
                        {%endfor%}
                        {% if is_paginated %}
                        <div class="col-lg-12 text-center">
                          
                            <div class="pagination__option">
                                {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
    
                                {%endif%}
                                <a class="page-item active" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                        
                                {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a>
                                {%endif%}
                            </div>
                        </div>
                        {%endif%}
                    </div>
                </div>
            </div>
        </div>
       
    </section>
 
    <!-- Shop Section End -->

    <!-- Instagram Begin -->
    {% include 'gallery.html'%}
    <!-- Instagram End -->

    <!-- Footer Section Begin -->
  
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery-ui.min.js"></script>
    <script src="js/mixitup.min.js"></script>
    <script src="js/jquery.countdown.min.js"></script>
    <script src="js/jquery.slicknav.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.nicescroll.min.js"></script>
    <script src="js/main.js"></script>

<!-- <script>var $grid = $('.grid').masonry({
    itemSelector: '.grid-item',
    percentPosition: true,
    columnWidth: '.grid-sizer'
  });
  
  // layout Masonry after each image loads
  $grid.imagesLoaded().progress( function() {
    $grid.masonry();
  });  </script> -->


</body>

{%endblock%}

commerce/templates/item_list.html
{% extends "base.html" %}

{% block content%}
<h2> Here is a list of our items </h2>
{% for item in items %}
{{item}}

{%endfor%}
{% endblock%}

commerce/templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

commerce/templates/navbar.html
{% load static %} {% load cart_template_tags %} 

<link
  href="https://fonts.googleapis.com/css2?family=Cookie&display=swap"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  crossorigin="anonymous"
/>
<header class="header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1">
        <div class="header__logo">
          <a href="{%url 'commerce:index' %}"
            ><img src="{% static 'img/logo.png' %}"
          /></a>
        </div>
      </div>
      <div class="col-md-8 col-xl-8 col-lg-6">
        <nav class="header__menu">
          <ul>
            <li class="active"><a href="{% url 'commerce:index'%}">Home</a></li>
            <li><a href="{% url 'commerce:string-arts' %}">String Arts</a></li>
            <li>
              <a href="{% url 'commerce:crotchets' %}">Crotchets</a>
              <ul class="dropdown">
                <li><a href="#">Crotchet Products</a></li>
                <li><a href="#">Crotchet Bags</a></li>
              </ul>
            </li>
            <li><a href="{% url 'commerce:yarnaccessories'%}"> Yarn & Accessories</a></li>
            <li><a href="{% url 'commerce:shop' %}">Shop</a></li>
            <li><span class="icon_search search-switch"></span></li>
           


         
          </ul>
        </nav>
      </div>
      <div class="col-md-3 col-lg-3">
        <div class="header__right">
          <div class="header__right__auth">
                     
                    </div>
          <ul class="header__right__widget">
            {% if request.user.is_authenticated %}
            <li><a href="#">{{request.user}}</a></li>
    
            <li><a href="{% url 'commerce:logout'%}">Logout</a></li>

            {% else %}
            <li><a href="{% url 'commerce:loginpage'%}">Login</a></li>
            <li><a href="{% url 'commerce:signuppage'%}">Register</a></li>
            {% endif %}

            <li>
              <a href="{% url 'commerce:shop-cart'%}"
                ><span class="icon_bag_alt"></span>
                <div class="tip"></div>
              </a>
            </li>
            <li>
              <ul class="dropdown-menu dropdown-menu-end">
                <li>
                  <a class="dropdown-item" href="#">
                    <div class="d-flex">
                      <div class="flex-shrink-0 me-3">
                        <div class="avatar avatar-online">
                          <img src="{% static 'adminDash/assets/img/avatars/myself.jpeg'%}" alt class="w-px-40 h-auto rounded-circle" />
                        </div>
                      </div>
                      <div class="flex-grow-1">
                        <span class="fw-semibold d-block">John Doe</span>
                        <small class="text-muted">Admin</small>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="dropdown-divider"></div>
                </li>
                <li>
                  <a class="dropdown-item" href="#">
                    <i class="bx bx-user me-2"></i>
                    <span class="align-middle">My Profile</span>
                  </a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">
                    <i class="bx bx-cog me-2"></i>
                    <span class="align-middle">Settings</span>
                  </a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">
                    <span class="d-flex align-items-center align-middle">
                      <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
                      <span class="flex-grow-1 align-middle">Billing</span>
                      <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
                    </span>
                  </a>
                </li>
                <li>
                  <div class="dropdown-divider"></div>
                </li>
                <li>
                  <a class="dropdown-item" href="auth-login-basic.html">
                    <i class="bx bx-power-off me-2"></i>
                    <span class="align-middle">Log Out</span>
                  </a>
                </li>
              </ul>
            </li>
            


          </ul>
        </div>
      </div>
    </div>
    <div class="canvas__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
  
</header>






</nav>





    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{% static 'adminDash/assets/vendor/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'adminDash/assets/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'adminDash/assets/vendor/js/bootstrap.js' %}"></script>
    <script src="{% static 'adminDash/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'adminDash/assets/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->
    <script src="{% static 'adminDash/assets/vendor/libs/apex-charts/apexcharts.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'adminDash/assets/js/main.js' %}"></script>

    <!-- Page JS -->
    <script src="{% static 'adminDash/assets/js/dashboards-analytics.js' %}"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

commerce/templates/search_form.html
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="d-flex" action="{%url 'commerce:search_product' %}">
            <input class="form-control me-2" type="search" placeholder="Search product" aria-label="Search" name="product_name" >
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
    </div>
</div> 

commerce/templates/wrapper.html
{% load static %}
{% load cart_template_tags %}
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__close">+</div>
    <ul class="offcanvas__widget">
        <li><span class="icon_search search-switch"></span></li>
        <li><a href="#"><span class="icon_heart_alt"></span>
            <div class="tip">2</div>
        </a></li>
        <li><a href="#"><span class="icon_bag_alt"></span>
            <div class="tip">3</div>
        </a></li>
    </ul>
    <div class="offcanvas__logo">
        <a href="{% url 'commerce:index'%}"><img src="{% static 'img/logo.png' %}" alt="logo should be"></a>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__auth">
        {% if request.user.is_authenticated %}
        <li><a href="#">{{request.user}}</a></li>

        <li><a href="{% url 'commerce:logout'%}">Logout</a></li>

        {% else %}
        <li><a href="{% url 'commerce:loginpage'%}">Login</a></li>
        <li><a href="{% url 'commerce:signuppage'%}">Register</a></li>
        {% endif %}
    </div>
</div>